name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"

  pull_request:
    branches:
      - main

jobs:
  build:
    uses: your-org/github-workflows/.github/workflows/build-and-deploy-to-wporg.yml@main
    with:
      plugin-slug: wp-w3tc-webp-helper
      deploy: false
    secrets: inherit